services:
  - type: web
    name: ai-product-ad-generator-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build --workspace=server
    startCommand: npm run start --workspace=server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
